<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Sivam" failures="1" tests="1" name="Test(failed)" time="0.068" errors="0" timestamp="2024-02-13T07:50:09 IST">
  <testcase classname="execuationpack.Test1" name="fitstTestCase" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at execuationpack.Test1.fitstTestCase(Test1.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- fitstTestCase -->
  <testcase classname="execuationpack.Test1" name="SecondTestCase" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTestCase -->
  <testcase classname="execuationpack.Test1" name="thirdTestCase" time="0.0">
    <ignored/>
  </testcase> <!-- thirdTestCase -->
</testsuite> <!-- Test(failed) -->
